### ISSUE TITLE
Conflict with other library with the same class name

### ISSUE THREAD

**Issue by q2amarket** [rlanvin/php-form#2]
I would suggest you to add namespace. I am using another library having the same class name `Form` . I am also reporting this to the other repo author

**Comment by rlanvin** [comment]
I understand, and of course you are right that `Form` is a very generic name. Unfortunately at the moment it is not possible to add a namespace. Using a namespace would mean that on every single file that uses this class you would have to add a `use` statement, or use a (more verbose) fully qualified class name. On the projects I am working on (and from where this lib has been extracted), this would result is a tremendous amount of extra code (not to mention the refactoring of hundreds of files). We felt that a namespace would make the library more annoying to use, and defeat the entire benefit of auto-loading the class, essentially replacing the need for `require` by the need for `use`.

That being said, as a work-around, I just pushed a commit, that should make it possible to use a namespace, if you want to. You should just be able to edit `Form.php` and `Validator.php` to add the `namespace` line at the beginning, and it should work without any other modification. You will also need probably need to change Composer's `autoloader` settings from `src` to something else (see [Composer doc](https://getcomposer.org/doc/04-schema.md#autoload))

Another workaround would be to simply change the class name to something else that `Form`. Again, it should work without any other modification, except the autoloader.

If you have other suggestions, please do tell. Also feel free to fork the repository and add the namespace if you want.
